version: '3.8'
services:
  mysql:
    build: ./SQL
    container_name: MySQLServer
    ports:
      - "3307:3307"
  app:
    build: .
    environment:
      - DB_HOST = ${DB_HOST}
      - DB_PORT = ${DB_PORT}
      - DB_PASSWORD = ${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - mysql